name: Release

on:
  push:
    tags:
      - v*

jobs:
  astra-release:
    runs-on: ubuntu-18.04
    env:
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

    steps:
      - name: Promote latest snapshot
        run: ./scripts/clean-latest.sh "$SNAPSHOT_DESC" "$GITHUB_REF"
